### ISSUE TITLE
Git history missing

### ISSUE THREAD

**Issue by est31** [briansmith/untrusted#30]
Currently, master of this git repo seems to stay on a commit from april 6, while the crates.io release is from July 4th, 2019.

**Comment by briansmith** [comment]
> Currently, master of this git repo seems to stay on a commit from april 6, while the crates.io release is from July 4th, 2019.

What's the difference between what's in the July 4th release and what's here?

**Comment by est31** [comment]
Hmm you are right, the vcs-info.json of the package points to commit 86ea9b774f73c085c269744a9e014ca8c19e97de
