### ISSUE TITLE
Build fails:"failed to resolve: use of undeclared type or module `cc`

### ISSUE THREAD

**Issue by mad-de** [briansmith/untrusted#31]
Building untrusted 0.7.0 as a dependency fails.

Steps to reproduce (eg):
`git clone -b undeclared_build_fail https://github.com/mad-de/IMPP/ IMPP_undeclared && cd IMPP_undeclared`
`cargo run --release`

Error message:

   Compiling untrusted v0.7.0
   Compiling byteorder v1.3.2
   Compiling smallvec v0.6.10
   Compiling getrandom v0.1.12
error[E0433]: failed to resolve: use of undeclared type or module `cc`
   --> /home/martin/.cargo/registry/src/github.com-1ecc6299db9ec823/untrusted-0.7.0/build.rs:465:21
    |
465 |         let mut c = cc::Build::new();
    |                     ^^ use of undeclared type or module `cc`

error[E0433]: failed to resolve: use of undeclared type or module `cc`
   --> /home/martin/.cargo/registry/src/github.com-1ecc6299db9ec823/untrusted-0.7.0/build.rs:538:17
    |
538 |     let mut c = cc::Build::new();
    |                 ^^ use of undeclared type or module `cc`

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0433`.
error: Could not compile `untrusted`.
warning: build failed, waiting for other jobs to finish...
error: build failed

**Comment by oherrala** [comment]
There's something not right here. Untrusted doesn't have `build.rs` file nor does require C compiler for building. The error is coming from something else.

```console
$ cargo vendor >/dev/null 2>&1
$ grep -ri "let mut c = cc::Build::new()" .
./vendor/ring/build.rs:        let mut c = cc::Build::new();
./vendor/ring/build.rs:    let mut c = cc::Build::new();
```

**Comment by mad-de** [comment]
> There's something not right here. Untrusted doesn't have `build.rs` file nor does require C compiler for building. The error is coming from something else.
> 
> ```
> $ cargo vendor >/dev/null 2>&1
> $ grep -ri "let mut c = cc::Build::new()" .
> ./vendor/ring/build.rs:        let mut c = cc::Build::new();
> ./vendor/ring/build.rs:    let mut c = cc::Build::new();
> ```

you are right. Some weird variable probably got stuck from an old build. I deleted my .carg/registry folder and it works now. Thanks for the help.
