### ISSUE TITLE
timeline for next release?

### ISSUE THREAD

**Issue by DanAlbert** [briansmith/untrusted#54]
Just a question rather than a bug :) Is there any timeline for a new release?

**Comment by briansmith** [comment]
I just released 0.8.0 from the current contents of `main`.

**Comment by DanAlbert** [comment]
Great, thanks!

**Comment by briansmith** [comment]
I ended up yanking the 0.8.0 release. Will file an issue in this issue tracker about it.

**Comment by briansmith** [comment]
@DanAlbert I'm curious, did you notice any problems with untrusted that make it important to upgrade from 0.7.1 to 0.8.0? Or, could you say more what's interesting about 0.8.0 to you? Thanks!

**Comment by DanAlbert** [comment]
It's a pretty minor thing. In Android we want to generate 
rustdocs for every crate we have in the tree, and untrusted 0.7.1 doesn't work with the latest version of rustdoc because it forbids all lints, and newer rustdoc lints more things (iirc an incorrect URL reference in a comment was the culprit). You fixed that by removing the forbid a while back but it hasn't made it into any release yet.

We've locally patched our version to allow the lint preventing us from generating the docs of course, but want to get back to a clean upstream released version when possible. No need to rush, of course :)
