### ISSUE TITLE
Add bit-field support

### ISSUE THREAD

**Issue by moosingin3space** [briansmith/untrusted#7]
If I want to parse IPv4 headers with `untrusted`, I need to be able to read a certain number of bits from the input. A portable bit-field-like reader would be very useful for this.

**Comment by briansmith** [comment]
> If I want to parse IPv4 headers with untrusted, I need to be able to read a certain number of bits from the input. A portable bit-field-like reader would be very useful for this.

I guess one would read the entire (multi)byte field using untrusted::Input, and then have a bit field parser that parses the bits using the proposed bit field reader, right? I guess I'd have to see an attempt to implement such a thing and a couple of uses of it before I could make progress adding it into untrusted. Perhaps try doing something like https://github.com/oherrala/untrustended did. Now I'm just getting around to looking at adding some of that functionality back into untrusted.

**Comment by briansmith** [comment]
I'm going to close this for now because I think it's not actionable as-is, but if/when somebody has something to point to, please LMK.
