### ISSUE TITLE
document minimum rustc version?

### ISSUE THREAD

**Issue by isonmad** [briansmith/untrusted#9]
Since 0dd059457651cc5b39a2ef4e01543c1d0e98fb7b made untrusted 0.5.0 and anything that depends on it require rustc 1.17, should this requirement be listed somewhere?

**Comment by briansmith** [comment]
I agree that this should be documented. In general it's the same as for *ring*: I only supported the latest version of untrusted, and the latest version of untrusted is only "supported" on the latest stable version of Rust. Effectively, the minimum version of Rust increases every six weeks, although often it will work on older releases.

**Comment by briansmith** [comment]
I documented this in 48c8b37d58d06f3d1ee17be83b267fae5ca362b6.
